baseURL = "https://unamatasanatarai.github.io/ksiazka-z-przepisami"
languageCode = "pl-pl"
defaultContentLanguage = "pl"
title = "Książka z przepisami"
theme = "przepisy"

[params]
  stylesheet = "/style.css"
  indexarticles = 500
